spring:
  datasource:
    url: jdbc:postgresql://localhost:5438/filestorage
    username: postgres
    password: password

  boot:
    admin:
      client:
        url: http://localhost:8085

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

minio:
  url: http://localhost:9000
server:
  port: 8088

