spring:
  data:
    redis:
      host: localhost
      port: 6379
      password:
      timeout: 6000ms
  datasource:
    url: jdbc:postgresql://localhost:5438/filestorage
    username: postgres
    password: password

  boot:
    admin:
      client:
        url: http://localhost:8085

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

minio:
  url: http://localhost:9000
server:
  port: 8088

cleaner-outbox-base-schedule-cron: "0 * * * * *"

bootstrapserver: localhost:29092

logging:
  level:
    com.lostway.cloudfilestorage.*: debug